/**
 * `.moa_cache/` 目录的 README 自动写入器（v0.14.10）
 *
 * 设计动机
 * --------
 * 作为一个会在用户工作区写入文件的插件，应该让用户随时能知道：
 *   1. 这个 `.moa_cache/` 目录是什么、谁写的、干什么用的
 *   2. 每个子目录的用途和保留价值（哪些是缓存可删、哪些是审计留档）
 *   3. 出问题时怎么诊断（识别 1213 dump、recon trace 等）
 *   4. 不需要时怎么清理（整体删除、按子目录删除、加 .gitignore）
 *   5. 想从缓存里挖有用内容（如 ref 输出、aggregator 综合）怎么定位
 *
 * 解法
 * ----
 * 任意一个写入 `.moa_cache/` 的代码路径（l3Summarizer / moaOrchestrator /
 * moaRunner.reconDump）在**首次创建目录时**调用 `ensureCacheReadme()`，
 * 在 `.moa_cache/README.md` 原子写入一份说明文档。
 *
 * - 已存在 README.md → 不覆盖（用户可能改过）
 * - workspace 不可用 → 静默跳过（不阻塞主流程）
 * - 写失败 → 只 console.warn，不影响 MoA 任务
 *
 * 文档语言：中英双语（中文为主，关键名词附英文），符合开源插件的国际友好度。
 */

import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

/** 当前 README 模板版本号 —— 改模板时递增。 */
const CACHE_README_VERSION = 3;

/** 插件仓库 URL（README 里用，便于用户查 issue）。 */
const REPO_URL = 'https://github.com/DDL095/vscode-moa';

/**
 * 构造 `.moa_cache/README.md` 的内容。
 * 导出以便单元测试 / 未来版本升级时迁移。
 */
export function buildCacheReadmeContent(): string {
  const generatedAt = new Date().toISOString();
  return [
    '# `.moa_cache/` — MoA Bridge 工作区缓存',
    '',
    `> This directory is auto-generated by the **[MoA Bridge](${REPO_URL})** VSCode extension.`,
    '> All files here are **safe to delete** — MoA will regenerate them on demand.',
    '>',
    `> Cache README v${CACHE_README_VERSION} · generated ${generatedAt}`,
    '>',
    '> ⚠️ **Autopilot mode is ON by default (v0.21.3+)** — After task convergence, the Actor role **auto-executes** `action_items` (write files, run terminal commands). SafeExecutor `.bak.<timestamp>` backup is applied. Audit: `<task_id>/manifest.json`. To disable: set `moa.executionPreset="manual"` or `"supervised"`.',
    '',
    '---',
    '',
    '## 这是什么 / What is this',
    '',
    '`@moa` chat participant 与 `moa_*` LM tools 在执行 Mixture-of-Agents 流水线时，',
    '会把**只读的中间产物**（recon 收集结果、ref 输出、aggregator 综合、L3 大文件摘要、',
    'orchestrate 状态）写到这个目录，便于：',
    '',
    '1. **调试 / 审计** — 看 recon 实际收集了什么、各 ref 说了什么、aggregator 怎么综合的',
    '2. **重放** — 把某次任务的 recon 数据喂给下次任务（通过 `moa_analyze` 的 `reconContext`）',
    '3. **缓存** — L3 大文件摘要同一文件 + 同一问题只算一次',
    '4. **跨会话恢复** — `moa_orchestrate` 的状态可跨 main-session compaction 续跑',
    '',
    '**这些文件不参与构建、不影响代码、不会被插件主动上传。**',
    '',
    '---',
    '',
    '## 目录结构 / Directory layout',
    '',
    '```',
    '.moa_cache/',
    '├── README.md                  # 本文件（v' + CACHE_README_VERSION + '，插件首次写入时生成，不自动覆盖）',
    '├── recon/<task_sha>/          # @moa 每次调用的端到端 trace（v0.14.3+）',
    '│   ├── meta.json              #   任务元信息（prompt / 时间 / 字符数）',
    '│   ├── 00_full_recon.md       #   注入 refs 的完整 recon summary',
    '│   ├── 01_captured/           #   recon agent 的每个工具调用（独立 md）',
    '│   │   └── 001_<toolname>.md',
    '│   ├── 02_ref_outputs/        #   每个 ref 的原始输出（多轮时带 _rN 后缀）',
    '│   │   └── ref1_<label>_<model>_r1.md',
    '│   ├── 03_aggregator.md       #   aggregator 综合（acting agent 的输入）',
    '│   └── 04_final.md            #   最终用户可见输出',
    '├── l3_summaries/<sha1>.txt    # L3 大文件摘要缓存（v0.13.0+，key=filePath+size+prompt）',
    '└── <task_id>/                 # moa_orchestrate 的迭代状态（v0.12.0+）',
    '    ├── state.json             #   当前 MoaState（原子覆盖写）',
    '    ├── task.txt               #   原始任务描述',
    '    ├── meta.json              #   跨轮累积元信息（含 ref_models / aggregator_model）',
    '    ├── timeline.md            #   全轮时序表（iteration / completeness / gaps）',
    '    ├── final.md               #   最终报告（含 summary + action_items + 收敛来源）',
    '    ├── iteration_NNN/         #   每轮的完整产物',
    '    │   ├── planner.json       #     Planner 输出（仅 iter 1）',
    '    │   ├── recon_result.json  #     Recon Aggregator 整合后的 summary（v0.18.0：始终写入）',
    '    │   ├── recon/             #     并行 Recon 子细节（v0.18.0：仅 parallel 模式生成）',
    '    │   │   └── recon_N.json   #       每个并行 recon agent 的 label/model/summary',
    '    │   ├── refs/              #     每个 ref 的原始输出（一个文件一个 ref）',
    '    │   │   └── ref1_<model>.json',
    '    │   ├── aggregator.json    #     Aggregator 综合（含 completeness / next_action）',
    '    │   └── actor_result.json  #     Actor 执行结果（仅 actor_needed 时）',
    '    └── final.json             #   #moa_finalize 的产出',
    '```',
    '',
    '---',
    '',
    '## 诊断与排查 / Diagnostics',
    '',
    '### 想知道某次 `@moa` 为什么输出那个结果',
    '',
    '1. 找最新的 `.moa_cache/recon/<task_sha>/` 目录（按 mtime 排序）',
    '2. 看 `meta.json` 确认 prompt 和时间',
    '3. 看 `00_full_recon.md` 确认 refs 实际看到了什么',
    '4. 看 `02_ref_outputs/` 下每个 ref 独立说了什么',
    '5. 看 `03_aggregator.md` vs `04_final.md` 对比 aggregator 综合 vs 最终输出',
    '',
    '### 想知道某次 `#moa_orchestrate` 迭代到第几轮、各轮 recon 收集了什么',
    '',
    '1. 进入 `.moa_cache/<task_id>/`',
    '2. 看 `timeline.md` 总览（9 列时序表：iter / time / completeness / Δ / gaps / recon tools / refs ok / actor / next）',
    '3. 进入 `iteration_NNN/`：',
    '   - `recon_result.json` 看 Recon Aggregator 整合后的 summary（始终有）',
    '   - `recon/recon_*.json` 看每个并行 Recon agent 的独立输出（仅 parallel 模式生成）',
    '   - `refs/*.json` 看每个 ref 说了什么',
    '   - `aggregator.json` 看 completeness 评分、next_action 决策、gaps',
    '   - `actor_result.json` 看 Actor 执行了哪些 action_items',
    '',
    '### 遇到 1213 / "empty content" 类错误',
    '',
    '- 检查 `02_ref_outputs/` 里是否有 ref 在中途返回了空',
    '- 检查 `01_captured/` 里工具调用结果是否被 `Part Diagnostics` 表标记为 "non-TextPart"',
    '- MoA v0.14.6+ 已增加 `extractTextFromNonTextPart` 容错；v0.14.7 已修复 ToolResultPart 空数组触发的 GLM 1213',
    '- 仍出问题请把 `recon/<task_sha>/` 整个目录打包到 issue',
    '',
    '### L3 摘要缓存疑似过期',
    '',
    '- L3 缓存 key = `sha1(filePath + fileSize + userPrompt 前 200 字符)`',
    '- 文件 mtime 不参与 key（单次任务内假设文件不变）',
    '- 想强制重算：删除 `.moa_cache/l3_summaries/<sha1>.txt`',
    '- 想完全禁用 L3：`"moa.l3Summarizer.model": ""`',
    '',
    '---',
    '',
    '## 清理策略 / Cleanup',
    '',
    '### 整体删除（最简单）',
    '',
    '```powershell',
    'Remove-Item -Recurse -Force .moa_cache/',
    '```',
    '',
    '```bash',
    'rm -rf .moa_cache/',
    '```',
    '',
    '→ 下次跑 `@moa` 时会重新创建（含本 README，因为本文件不在时才写）。',
    '',
    '### 按子目录清理',
    '',
    '| 想清理的 | 删什么 | 影响 |',
    '|---|---|---|',
    '| 全部 recon trace（占空间最大） | `.moa_cache/recon/` | 仅失去历史审计，不影响功能 |',
    '| 某次失败任务 | `.moa_cache/recon/<task_sha>/` | 同上 |',
    '| L3 大文件摘要缓存 | `.moa_cache/l3_summaries/` | 下次大文件需要重新摘要 |',
    '| 未完成的 orchestrate 任务 | `.moa_cache/<task_id>/` | 已 finalize 的不受影响 |',
    '',
    '### 想提取有用内容',
    '',
    '- **某次 ref 分析写得很好想留底**：从 `02_ref_outputs/refN_*.md` 复制走',
    '- **aggregator 综合想用作其他用途**：复制 `03_aggregator.md`',
    '- **想拿完整 recon 数据喂给别的工具**：用 `00_full_recon.md`',
    '',
    '---',
    '',
    '## `.gitignore` 建议',
    '',
    '建议把 `.moa_cache/` 加入项目 `.gitignore`，避免把大文件摘要和中间产物提交进版本控制：',
    '',
    '```gitignore',
    '# MoA Bridge cache (auto-generated by vscode-moa extension)',
    '.moa_cache/',
    '```',
    '',
    '如果你确实想把某次任务的 trace 留档提交（比如写教程），可以单独 force-add：',
    '',
    '```bash',
    'git add -f .moa_cache/recon/<task_sha>/',
    '```',
    '',
    '---',
    '',
    '## 配置项 / Configuration',
    '',
    '以下 `moa.*` 配置项影响这个目录的写入行为（在 VSCode `settings.json` 里改）：',
    '',
    '| Key | 默认 | 影响 |',
    '|---|---|---|',
    '| `moa.executionPreset` | **`autopilot`** (v0.21.3+) | `autopilot` = finalize 后自动执行 action_items；`manual` = 只返回 markdown；`supervised` = Gate-A 审批；`yolo` = 无备份裸跑 |',
    '| `moa.enableActorInLoop` | **`true`** (v0.21.3+) | Loop 内 Actor 角色是否启用（false 时 `actor_needed` 降级为 `recon_needed`） |',
    '| `moa.enableRecon` | `true` | `false` 时跳过 Phase 0，不产生 `recon/` 新目录 |',
    '| `moa.l3Summarizer.model` | `""` (disabled) | 空字符串完全禁用 L3，不产生 `l3_summaries/` |',
    '| `moa.reconL3Threshold` | `200000` | 单文件超过多少字符才触发 L3 摘要 |',
    '| `moa.reconL3MaxCalls` | `5` | 单次任务最多派几次 L3 孙代理 |',
    '| `moa.reconL3TargetChars` | `100000` (v0.21.3+) | L3 单文件精选后的目标输出长度 |',
    '| `moa.maxReconRounds` | `5` (v0.21.3+) | **单任务内** recon 循环轮数（仅 @moasingle + moa_analyze；@moa/@moaloop 用 MAX_ITER=12） |',
    '| `moa.maxReconIterations` | `100` (v0.21.3+) | recon agent 单轮最多工具调用次数 |',
    '| `moa.reconAllowTerminal` | **`true`** (v0.21.3+) | 允许 recon 用 terminal（runInTerminal 等） |',
    '| `moa.parallelRecon` | `true` | v0.18.0：并行多模型 Recon（影响 `iteration_NNN/recon/` 是否生成） |',
    '| `moa.cacheTtlDays` | **`0`** (v0.21.3+) | 0 = 永不自动清理（需手动删除 .moa_cache/） |',
    '',
    '**禁用一切写入**：目前没有一个总开关；最干净的做法是 `moa.enableRecon=false` + `moa.l3Summarizer.model=""`，',
    '剩下 `moa_orchestrate` 工具的状态文件仅在使用该工具时产生（不用即不写）。',
    '',
    '---',
    '',
    '## 隐私 / Privacy',
    '',
    '- `.moa_cache/` 只在**本地文件系统**写入，MoA Bridge 插件本身**不**上传任何文件',
    '- 但当 MoA 把 recon 内容发给配置的 LLM（refs/aggregator）时，那些内容会按各家 provider 的隐私政策处理',
    '- 如有敏感代码 / 密钥 / 内部数据，**不要**让 MoA 处理，或先在 `moa.reconBlockedTools` / recon 系统提示里加白名单约束',
    '',
    '---',
    '',
    `更多文档见 [项目 README](${REPO_URL}#readme) · [CHANGELOG](${REPO_URL}/blob/main/CHANGELOG.md) · [Issues](${REPO_URL}/issues)`,
    '',
  ].join('\n');
}

/**
 * 在 `.moa_cache/` 目录下确保有一份 README.md。
 *
 * 调用时机：**任意写入 `.moa_cache/` 的代码路径**在创建目录时调用一次。
 * 已存在则不覆盖（尊重用户修改）。
 *
 * @param cacheRoot 例如 `<workspace>/.moa_cache`
 * @returns 写入成功返回 true；已存在 / 失败 / workspace 不可用 返回 false
 */
export function ensureCacheReadme(cacheRoot: string): boolean {
  try {
    if (!cacheRoot || typeof cacheRoot !== 'string') return false;

    // 目录不存在先尝试创建（理论上调用方已创建，但稳妥起见）
    if (!fs.existsSync(cacheRoot)) {
      fs.mkdirSync(cacheRoot, { recursive: true });
    }

    const readmePath = path.join(cacheRoot, 'README.md');

    // v0.21.3: 版本升级时强制覆盖（让用户看到新的 autopilot 警告）
    //   读现有 README 头部的 "Cache README vN" 提取版本号
    //   若不存在或版本低于 CACHE_README_VERSION → 覆盖
    //   若版本等于当前 → 不覆盖（尊重用户修改）
    if (fs.existsSync(readmePath)) {
      try {
        const existing = fs.readFileSync(readmePath, 'utf8');
        const m = existing.match(/Cache README v(\d+)/);
        const existingVer = m ? parseInt(m[1], 10) : 0;
        if (existingVer >= CACHE_README_VERSION) {
          return false;  // 已是最新版本，不覆盖
        }
        // 版本低于当前 → 继续覆盖
      } catch {
        // 读失败 → 不覆盖（保守）
        return false;
      }
    }

    const content = buildCacheReadmeContent();

    // 原子写入：先写 tmp 再 rename，避免被并发读取到半写状态
    const tmpPath = `${readmePath}.tmp`;
    fs.writeFileSync(tmpPath, content, 'utf8');
    fs.renameSync(tmpPath, readmePath);

    return true;
  } catch (err) {
    // 写失败不阻塞主流程，只 console.warn
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`[MoA cacheReadme] failed to write README.md: ${msg}`);
    return false;
  }
}

/**
 * 便捷封装：直接从 vscode.workspace 推断 cacheRoot 并写入。
 *
 * 用于不想自己拼路径的调用方（典型场景）。
 */
export function ensureDefaultCacheReadme(): boolean {
  const ws = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
  if (!ws) return false;
  const cacheRoot = path.join(ws, '.moa_cache');
  return ensureCacheReadme(cacheRoot);
}
