/**
 * Type definitions for MoA Bridge chat participant.
 */

import type { ChatParticipantToolToken } from 'vscode';

/**
 * Execution path for MoA workflow.
 *
 * v0.7.2: only P1 native (vscode.lm) is implemented. The P2a/P2b paths were
 * removed (unimplemented / unused). Kept the union for forward-compat with
 * future direct-HTTP mode.
 */
export type MoaPath = 'P1' | 'P1-partial' | 'P1-degraded' | 'error';

/**
 * Result of running the MoA fan-out + aggregate flow.
 */
export interface MoaRunResult {
  /** Final aggregated output (Markdown). */
  output: string;
  /** Wall-clock elapsed seconds. */
  elapsed: number;
  /** Path that was actually used. */
  path: MoaPath;
}

/**
 * Lightweight structured prompt for vscode.lm.
 */
export interface ChatMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

/**
 * A reference advisor entry — equal-mode MoA (v2).
 *
 * Stored in `moa.refModels` setting (array). All refs share the same prompt
 * (`moa.sharedRefPrompt`); the model difference provides diversity.
 */
export interface RefModelConfig {
  /**
   * Display label for this advisor, e.g. "advisor_1". Auto-generated by
   * the Configure Models command. Not injected into the prompt in v2.
   */
  role: string;
  /** Substring to match against vscode.lm model name, e.g. "GLM-5.2". */
  model: string;
  /**
   * Deprecated in v2 (equal mode). Kept for backward compat — parsed but
   * ignored at runtime. Use `moa.sharedRefPrompt` instead.
   * @deprecated v2 equal-mode MoA ignores per-ref systemHint.
   */
  systemHint?: string;
}

/**
 * Aggregator model config.
 */
export interface AggregatorConfig {
  /** Substring to match against vscode.lm model name. */
  model: string;
  /** Optional temperature (currently informational; vscode.lm doesn't expose per-call temp). */
  temperature?: number;
}

/**
 * Re-export helper to keep imports tidy in other files.
 */
export type { ChatParticipantToolToken };