/**
 * Type definitions for MoA Bridge chat participant.
 */

import type { ChatParticipantToolToken } from 'vscode';

/**
 * Execution path for MoA workflow.
 *
 * v0.7.2: only P1 native (vscode.lm) is implemented. The P2a/P2b paths were
 * removed (unimplemented / unused). Kept the union for forward-compat with
 * future direct-HTTP mode.
 */
export type MoaPath = 'P1' | 'P1-partial' | 'P1-degraded' | 'error';

/**
 * Result of running the MoA fan-out + aggregate flow.
 */
export interface MoaRunResult {
  /** Final aggregated output (Markdown). */
  output: string;
  /** Wall-clock elapsed seconds. */
  elapsed: number;
  /** Path that was actually used. */
  path: MoaPath;
}

/**
 * Lightweight structured prompt for vscode.lm.
 */
export interface ChatMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

/**
 * A reference advisor entry — equal-mode MoA (v2).
 *
 * Stored in `moa.refModels` setting (array). All refs share the same prompt
 * (`moa.sharedRefPrompt`); the model difference provides diversity.
 */
export interface RefModelConfig {
  /**
   * Display label for this advisor, e.g. "advisor_1". Auto-generated by
   * the Configure Models command. Not injected into the prompt in v2.
   */
  role: string;
  /** Substring to match against vscode.lm model name, e.g. "GLM-5.2". */
  model: string;
  /**
   * Deprecated in v2 (equal mode). Kept for backward compat — parsed but
   * ignored at runtime. Use `moa.sharedRefPrompt` instead.
   * @deprecated v2 equal-mode MoA ignores per-ref systemHint.
   */
  systemHint?: string;
}

/**
 * Aggregator model config.
 */
export interface AggregatorConfig {
  /** Substring to match against vscode.lm model name. */
  model: string;
  /** Optional temperature (currently informational; vscode.lm doesn't expose per-call temp). */
  temperature?: number;
}

/**
 * v0.14.0: Recon agent 专用模型配置。
 *
 * 设计：
 *   - 用户可通过 "Moa: Configure Models" Step 3/4 单独指定 recon 用的模型
 *   - 留空（model=''）= fallback 到 aggregator 模型（保持 v0.13.x 行为）
 *   - 推荐选工具调用稳定的模型（GLM-5.2 / DeepSeek-V4-Pro）
 *
 * 与 AggregatorConfig 字段一致（model + temperature），但 temperature 实际
 * 未被 vscode.lm API 使用，仅保留以便未来扩展。
 */
export interface ReconConfig {
  /**
   * 模型 ID（vscode.lm 的 m.id，如 "gcmp.zhipu:::GLM-5.2-CodingPlan"）。
   * 空字符串 = fallback 到 aggregator 模型（向后兼容 v0.13.x）。
   */
  model: string;
  /** Optional temperature（暂未使用，预留扩展）。 */
  temperature?: number;
}

/**
 * v0.14.0: L3 孙代理（大文件精选器）模型配置。
 *
 * 设计：
 *   - 用户可通过 "Moa: Configure Models" Step 4/4 单独指定 L3 用的模型
 *   - 留空（model=''）= 完全禁用 L3，所有大文件走 L2 语义边界截断
 *   - 默认推荐 MiniMax-M3（CLAUDE.md §2.4 两层嵌套规则要求 M3）
 *
 * 移植性：把 modelId 从硬编码常量（v0.13.0 的 DEFAULT_L3_MODEL_ID）
 * 改为配置项，避免换环境后失效。
 */
export interface L3Config {
  /**
   * 模型 ID（vscode.lm 的 m.id）。
   * 空字符串 = 禁用 L3（所有大文件降级到 L2 语义边界截断）。
   */
  model: string;
}

/**
 * Re-export helper to keep imports tidy in other files.
 */
export type { ChatParticipantToolToken };